default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: themakingcollective_development

test:
  <<: *default
  database: themakingcollective_test

production:
  <<: *default
  database: themakingcollective_production
